### ISSUE TITLE
not working :net::ERR_ABORTED 504 (Outdated Optimize Dep)

### ISSUE THREAD

**Issue by ahmadkashami** [paul-thebaud/v-phone-input#11]
GET http://localhost:5173/node_modules/.vite/deps/v-phone-input.js?v=2add29de net::ERR_ABORTED 504 (Outdated Optimize Dep)

**Comment by paul-thebaud** [comment]
Hi @ahmadkashami,
Thank you for your issue. Without any further details, I cannot investigate the issue.
Could you provide a reproduction repo please?

**Comment by ahmadkashami** [comment]
Thank you for your quick response, this problem no longer appears when the server is restarted
