### ISSUE TITLE
docs: per input searching country doc is outdated (example does not work)

### ISSUE THREAD

**Issue by warrence** [paul-thebaud/v-phone-input#14]
hi, when i try to enable enable-searching-country, the country dropdown selection field is gone.

```

<VPhoneInput
                  v-model="phone"
                  default-country="MY"
                  country-icon-mode="text"
                  enable-searching-country
                />

```

**Comment by paul-thebaud** [comment]
Hi @warrence, could you please tell me the VPhoneInput / Vuetify / Vue versions you are using?

Did you fully read the enabling searching countries guide?

- [Guide for V3 (vuetify 3)](https://github.com/paul-thebaud/v-phone-input#enabling-searching-countries)
- [Guide for V2 (vuetify 2)](https://github.com/paul-thebaud/v-phone-input/tree/2.x.x#enabling-searching-countries)

**Comment by warrence** [comment]
v-phone-input 3.0.5
Vuetify 3.2.1
vue 3.2.47

Yes i follow the guide in V3.  Will that be an issue if im using typescript?

**Comment by warrence** [comment]
just tested with an empty vuetify project without typescript, also having same problem.

**Comment by warrence** [comment]
I got it working now, im not sure why but even if im using per-input basis...importing VAutocomplete in the component file wont help.

What i do to make it work is add the code below into my main.js

```js
import { VAutocomplete } from 'vuetify/lib/components/index.mjs'

const app = createApp(App)
```

**Comment by paul-thebaud** [comment]
@warrence, my bad. The per input documentation for importing autocomplete input is outdated and won't work. Autocomplete input must be globally registered to work. I'll update the docs soon.
Thanks for your investigation.

**Comment by warrence** [comment]
No worry at all man. Thanks for the prompt response and the great plugin!

**Comment by paul-thebaud** [comment]
Hi @warrence, I update the [readme section about enabling searching country](https://github.com/paul-thebaud/v-phone-input#enabling-searching-countries). Thanks again for your report.
