### ISSUE TITLE
question: changing invalid message

### ISSUE THREAD

**Issue by warrence** [paul-thebaud/v-phone-input#15]
The "Phone" field is not a valid phone number (example: 03-2385 6789).

Hi may i know if i could change the default message for this? Actually I'm building multi language site, and i would like to change it to use vueI18n as below

$t('The "Phone" field is not a valid phone number (example: 03-2385 6789).')

**Comment by paul-thebaud** [comment]
Since this is a question, I'm closing as answered. Feel free to open a new issue if needed.

**Comment by warrence** [comment]
Hi there thanks for the response.Yes it was the latest 3.0.5. I tried to follow the documentation, and I'm getting error

TypeError: n.component is not a function

I'm using the example from the docs
```js
const VPhoneInput = createVPhoneInput({
  label: 'Phone number',
  countryLabel: 'Country',
  countryAriaLabel: ({ label }) => `Country for ${label}`,
  invalidMessage: ({ label, example }) =>
    `${label} must be a valid phone number (example: ${example}).`,
})
```

**Comment by paul-thebaud** [comment]
The only place where a `.component` is used by the package is inside the Vue plugin registration, so maybe this part of your code is wrong. As a reminder, the `VPhoneInput` plugin created by `createVPhoneInput` should be "used" in your Vue app creation, such as:

```js
import 'flag-icons/css/flag-icons.min.css';
import 'v-phone-input/dist/v-phone-input.css';
import { createVPhoneInput } from 'v-phone-input';
import { createApp } from 'vue';

// Vue app creation.
const app = createApp(App);

// VPhoneInput plugin creation.
const VPhoneInput = createVPhoneInput({
  // ... your options ...
});

// VPhoneInput plugin registration.
app.use(vPhoneInput);

// Vue app mounting.
app.mount('#app');
```

In all cases, it looks like this error has nothing related to the messages customization feature or the package.
Tell me if I can do anything else.
