### ISSUE TITLE
bug: invalid phone number 

### ISSUE THREAD

**Issue by Keyur-C-Shah** [paul-thebaud/v-phone-input#16]
## Expected Behavior
Found a couple of series shows invalid phone number, though they are valid: eg: 0493780000 country:Australia

## Actual Behavior
Above series should be valid without errors check https://vue-tel-input.iamstevendao.com/

## Steps to Reproduce the Problem

  1. paste the above mentioned number in example, it will show invalid
  1.
  1.

## Specifications

  - OS: All
  - Browser: Chrome
  - Browser version: Latest
  - Package version: Latest
  - Vuetify version:

**Comment by paul-thebaud** [comment]
Hello @Keyur-C-Shah, this issue is due to `awesome-phonenumber` V3 used in the package.
I'm currently migrating to V6, this will soon be released as `v-phone-number` V4, since `awesome-phonenumber` V4 contained breaking change to functions signatures.

**Comment by paul-thebaud** [comment]
Fix released in v4.0.0. Closing the issue.
