### ISSUE TITLE
bug: preferCountries doesn't seem to work

### ISSUE THREAD

**Issue by yqgit** [paul-thebaud/v-phone-input#17]
When I add a preferCountries array as mentioned in the documentation, it doesn't seem to do anything
`<VPhoneInput
    v-model="phoneNumber"
    country="FR"
    :prefer-countries="['FR', 'BE', 'IT', 'ES', 'DE', 'LU']"
  />`

**Comment by paul-thebaud** [comment]
Confirmed. I'm working on a fix which will be released soon!

**Comment by paul-thebaud** [comment]
Thank you for the issue @yqgit.
Fix released in [`v4.0.1`](https://github.com/paul-thebaud/v-phone-input/compare/v4.0.0...v4.0.1) :tada:
