### ISSUE TITLE
feat: preferCountries should be sorted as they are ordered on the array.

### ISSUE THREAD

**Issue by ricardo17coelho** [paul-thebaud/v-phone-input#19]
## Expected Behavior
If `preferCountries ` are defined, they should be sorted as defined by the array and not alphabetically.

## Actual Behavior
Defined `preferCountries` are sorted alphabetically 

## Steps to Reproduce the Problem

```
...
preferCountries: ['CH', 'IT', 'FR', 'DE', 'AT', 'LI']
...
```

**Comment by paul-thebaud** [comment]
@ricardo17coelho 
Preferred countries will now be ordered using the passed `preferCountries` prop in `v4.1.0` :tada:

**Comment by ricardo17coelho** [comment]
Thx 🙏 @paul-thebaud
