### ISSUE TITLE
feat: add prop 'example'

### ISSUE THREAD

**Issue by ricardo17coelho** [paul-thebaud/v-phone-input#20]
## Expected Behavior
In order to be possible to display an more "realistic" example would be nice if there is an "example" prop to be possible to provide the example value

## Actual Behavior

Example is auto-generated

**Comment by paul-thebaud** [comment]
Hi @ricardo17coelho,
What's the point on this? Example is automatically generated depending on the country, because it should not be same from a country to another. What do you expect for this new prop? Passing a string example or an example generation callback function?

**Comment by ricardo17coelho** [comment]
Hi @paul-thebaud 

An example "string" would be nice.
For ex: for swiss number, the format is like: 012 456 78 90 and i want the example as: 079 000 00 00 in order to be more realistic.
Generally i think this "possibility" would give the users more flexibilitiy.
If the prop example is not overrided the component should use the internall generator.
thx :)

**Comment by paul-thebaud** [comment]
@ricardo17coelho 
New `example` prop have been added inside `v4.1.0` :tada:
It support a string or a callback to generate the example based on a country object!

**Comment by ricardo17coelho** [comment]
Thx 🙏 @paul-thebaud
