### ISSUE TITLE
question: country input height and hiding details

### ISSUE THREAD

**Issue by Minotti** [paul-thebaud/v-phone-input#22]
## Expected Behavior
![Screenshot 2024-01-17 at 19 20 09](https://github.com/paul-thebaud/v-phone-input/assets/17681478/76b14245-6e8a-4ff2-87fa-fcf64918540a)

As can you see, the demo preview works perfectly.

## Actual Behavior
Error 1. With option _enableSearchingCountry_ enabled:
![Screenshot 2024-01-17 at 19 20 03](https://github.com/paul-thebaud/v-phone-input/assets/17681478/6b631a8b-b69b-4247-8eae-bf7f277eab19)
The height is incorrectly and has gray background instead white.

Error 2. With defaults options:
![Screenshot 2024-01-17 at 19 27 40](https://github.com/paul-thebaud/v-phone-input/assets/17681478/1bbf8481-5b25-4e65-9f17-fc1d9a5606c8)
The height keep still incorrect, but background are normal.

And another thing, how can i remove messages below input? In Vuetify is a property _hide-details_, but here i didn't found out.

## Steps to Reproduce the Problem

  1. Follow instructions
  2. Enable country search to see Error 1
  3. To reproduce error 2 only keep default options on _createVPhoneInput_

## Specifications

  - OS: MacOS
  - Browser: Google Chrome 
  - Browser version: Version 120.0.6099.234 (Official Build) (arm64)
  - Package version: 4.1.0
  - Vuetify version: 3.3.8
  - Vue version: 3.2.31

Best regards

**Comment by paul-thebaud** [comment]
Hi @Minotti, looks like you are not using the latest version of Vuetify. This could lead to this height problem. Please confirm here if it fix your problem.

Don't known about the background, but it looks OK on the demo (for all input styles). This other style problem might comes from your own styles.

Finally, as stated by the docs, "_You can also pass the [Vuetify VTextField](https://vuetifyjs.com/en/api/v-text-field/#props) and [Vuetify VSelect](https://vuetifyjs.com/en/api/v-select/#props) props_": so you can just use `hide-details` on the field. Keep in mind that hidding error message is bad for accessibility as users won't get a feedback on what's wrong with their input (some users may not even know about the error if the only flag for it is the input border color).

**Comment by Minotti** [comment]
Hello @paul-thebaud , thanks for reply.

I will try upgrade vuetify version and i believe is that. 

About background, It makes sense to be something here in my project, after all, I bought a template.

Thanks for that.
