### ISSUE TITLE
Tutorial: Nuxt 3 Tutorial

### ISSUE THREAD

**Issue by z0lo13** [paul-thebaud/v-phone-input#23]
create file
1. v-phone-input.client.ts inside plugins

2. Put Code:
```
import 'v-phone-input/dist/v-phone-input.css';
import 'flag-icons/css/flag-icons.min.css';
// @ts-ignore
import { createVPhoneInput } from 'v-phone-input';

export default defineNuxtPlugin((nuxtApp) => {
    const vPhoneInput = createVPhoneInput({
        label: 'Your phone number',
        countryIconMode: 'svg',
    });
    nuxtApp.vueApp.use(vPhoneInput)
})
```

3. In a component use like in readme

**Comment by paul-thebaud** [comment]
Hello @z0lo13, is this a question or a tutorial to use this on nuxt ?

**Comment by z0lo13** [comment]
> Hello @z0lo13, is this a question or a tutorial to use this on nuxt?

My bad, didn't change the template. It is a tutorial indeed.

**Comment by paul-thebaud** [comment]
Thanks @z0lo13, I'm closing as this is not an issue and people will still be able to check it inside closed issues.
