### ISSUE TITLE
question: the country code will be lost. If open country search in version 4.1.1，enable-searching-country

### ISSUE THREAD

**Issue by ydedev** [paul-thebaud/v-phone-input#25]
## Expected Behavior
 
display country code

## Actual Behavior

country code missing

enable-searching-country Field，If closed, it will return to normal

test code : https://github.com/ydedev/test-v-phone-input

<img width="464" alt="image" src="https://github.com/paul-thebaud/v-phone-input/assets/136344088/fb35a486-1ff3-4651-bdcc-c8f329f96017">

**Comment by paul-thebaud** [comment]
Hello @ydedev,

## Solution to your problem

As stated [per the documentation](https://github.com/paul-thebaud/v-phone-input?tab=readme-ov-file#when-using-plugin-registration) :

> To enable searching countries for all inputs as a default behavior, you must register the VAutocomplete component globally inside your plugin definition.

In your `main.js` file, you should import and register `VAutocomplete`:

```javascript
import { VAutocomplete } from 'vuetify/components/VAutocomplete';

app.component('VAutocomplete', VAutocomplete);
```
## Side notes

Please take the time to correctly read the documentation and check your build/dev errors before submitting issue (I'm pretty sure you got a "no VAutocomplete component registered" error in your browser console).

That being said, thanks for giving a reproduction repository, this helps a lot finding errors/bugs. However, please make the simplest repository possible (only two files are important in yours: `main.js` and `views/Home.view`).
