### ISSUE TITLE
question: how to confirm if phone number is valid?

### ISSUE THREAD

**Issue by singhgursharnbir** [paul-thebaud/v-phone-input#28]
I tried looking up documentations and everything, the v-model and update:modelValue always give back phone number does not matter is it valid or not?

**Comment by paul-thebaud** [comment]
Hello @singhgursharnbir,
Phone is returned on model independently from the valid state of it, because validation is handled using Vuetify `rules` system.
If you want to validate it outside of the classic, validation process, you can use awesome-phonenumber library or the `makePhone` utility method.

```typescript
import { makePhone } from 'v-phone-input';
import { parsePhoneNumber } from 'awesome-phonenumber';

const phoneString = '+33...';

const phoneObject = makePhone(phoneString);
// OR
const phoneObject = parsePhoneNumber(phoneString);

// Check valid state.
console.log(phoneObject.valid);
```

**Comment by singhgursharnbir** [comment]
Just after I opened this ticket, I looked into the github page and then I backtracked it! Thanks for the plugin!

**Comment by paul-thebaud** [comment]
Nice, you're welcome 😉
