### ISSUE TITLE
question: accepting emergency numbers(3-4 digits) / trying to overwrite all the rules(using rules prop)

### ISSUE THREAD

**Issue by Techbinator** [paul-thebaud/v-phone-input#31]
## Description

I would to modify the validation in order to allow emergency numbers(3-4 digits) like:

Police: 117
Fire service: 118
Medical service: 144

I tried the `rules` prop but that seems to add extra validation on top of the one that is already provided.

Is there an workaround that would allow me to overwrite all the built in validation rules or a prop that would allow this type of numbers?

## Expected Behavior

When passing the `rules` prop it should overwrite all the other validations

## Actual Behavior

When rules prop is passed it simply adds extra `rules` on top of the built in ones

## Steps to Reproduce the Problem

  1. Try to enter a emergency number ex 117
  2. Throws an error even if rules prop is overwritten

## Specifications

 Latest version

**Comment by paul-thebaud** [comment]
Hello @Techbinator,
You can disable built-in validation by passing a `null` `invalidMessage` property as follow:

```vue
<v-phone-input
  :invalid-message="null"
/>
```

However, using VPhoneInput for your current requirement may not be a good idea, as it will try to format the number to E164 according to the given country (e.g. `+3318` with `18` input for France).

**Comment by paul-thebaud** [comment]
@Techbinator I will add a note on the default validation by-passing on README, feel free to reopen this issue if it is not resolved.

**Comment by paul-thebaud** [comment]
Hello @Techbinator, support for this feature has been released inside `v5.0.0` 🎉
You can use [`phoneValidator` property](https://github.com/paul-thebaud/v-phone-input?tab=readme-ov-file#custom-phone-number-validator) to customize the phone validation behavior, and support short numbers.
