### ISSUE TITLE
question: hideDetails attribute

### ISSUE THREAD

**Issue by louis49** [paul-thebaud/v-phone-input#34]
Can we rename the hideDetails attribute to hide-details to conform to what Vuetify practices?

## Expected Behavior
 <v-phone-input v-model="phone"
                     v-model:country="country"
                     class="phone-input-layout"
                     :label="$t('signup_phone_number_hint')"
                     :country-label="$t('signup_country_hint')"
                     :guessCountry="true"
                     hide-details>

=> This not hide details

## Actual Behavior
 <v-phone-input v-model="phone"
                     v-model:country="country"
                     class="phone-input-layout"
                     :label="$t('signup_phone_number_hint')"
                     :country-label="$t('signup_country_hint')"
                     :guessCountry="true"
                     hideDetails>
=> This hide details

**Comment by paul-thebaud** [comment]
In Vue, props are defined camel case in components (`hideDetails`) and can be passed camel or kebab case (`hide-details`). So this is already supported.
