### ISSUE TITLE
question: after building the field will be separate v-text-field and v-select

### ISSUE THREAD

**Issue by HudaNasih** [paul-thebaud/v-phone-input#38]
## Expected Behavior
The phone field is getting separate v-text-field and v-select or v-auto-complete

```ts
import Vue from 'vue'
// v-phone-input:  https://github.com/paul-thebaud/v-phone-input/tree/2.x.x
import { createVPhoneInput } from 'v-phone-input'
import 'v-phone-input/dist/v-phone-input.css'

import { VAutocomplete, VSelect } from 'vuetify/lib'
import i18n from '@/plugins/i18n'
// Globally import VAutocomplete, IMPORTANT: required when tree shaking Vuetify components.
Vue.component('VAutocomplete', VAutocomplete)
Vue.component('VSelect', VSelect)

const vPhoneInput = createVPhoneInput({
  countryLabel: `${i18n.t('label.code')}`
})

// Configure VPhoneInput library.
Vue.use(vPhoneInput)
```

In the local host
![image](https://github.com/paul-thebaud/v-phone-input/assets/29692659/90840429-c49b-4ae3-9e6d-65f3015a75f4)

after building the project it will be rendered like that
![image](https://github.com/paul-thebaud/v-phone-input/assets/29692659/f1872c36-89e7-492c-90e4-47c18a105ed7)

## Specifications

  - OS: Windows
  - Browser: Brave
  - Browser version: latest
  - Package version: 2.0.1
  - Vuetify version: 2.7.1

**Comment by paul-thebaud** [comment]
Hello, looks like CSS is missing in your production build. Please provide a stackblitz or GitHub reproduction if you need help.

**Comment by HudaNasih** [comment]
Hello,
I just statically set the style inside the component to solve it for now,
Thank you
