### ISSUE TITLE
feat: show country code alongside flag icon

### ISSUE THREAD

**Issue by bishwajitcadhikary** [paul-thebaud/v-phone-input#39]
Is there a feature available to display the country code along with a flag icon?

**Comment by paul-thebaud** [comment]
Hello @bishwajitcadhikary, do you mean like inside the country input selection slot?

Such as:
![image](https://github.com/user-attachments/assets/c49eb48a-37b2-418f-81c1-c708539a7c94)

**Comment by bishwajitcadhikary** [comment]
Yes

**Comment by paul-thebaud** [comment]
Hello @bishwajitcadhikary, you can now do this easily in `v4.3.0` :tada:

You need to pass a `#country-selection` slot, like in the following example (when using SVG icon). Depending on your selection content, you may need to change the default country input width with a custom CSS.

```vue
<script setup>
import { VCountryIconSvg } from 'v-phone-input';
</script>

<template>
  <v-phone-input>
    <template #country-selection="{ country }">
      <v-country-icon-svg
        :country="country"
        class="mr-2"
      />
      {{ country.iso2 }}
    </template>
  </v-phone-input>
</template>

<style>
  .v-phone-input .v-phone-input__country__input .v-field {
    --v-phone-input-country-width: 8rem !important;
  }
</style>
```

**Comment by bishwajitcadhikary** [comment]
If you can add the area code, that would be great.

**Comment by paul-thebaud** [comment]
What do you mean by "area code"?

**Comment by bishwajitcadhikary** [comment]
Yes for example +880, +44 etc

**Comment by paul-thebaud** [comment]
Are you searching for the [`dialCode` prop](https://github.com/paul-thebaud/v-phone-input?tab=readme-ov-file#country)?
As an example, it is `33` for France.
