### ISSUE TITLE
an error appears when using the package in vue 3

### ISSUE THREAD

**Issue by ahmedabdelhafez** [paul-thebaud/v-phone-input#4]
## Expected Behavior
app work and phone input appears
## Actual Behavior
this error appears in browser and app not working till remove th package
![image](https://user-images.githubusercontent.com/25756993/174487935-88c2b4c8-9838-4aee-ace1-dccb6c64b14d.png)

**Comment by paul-thebaud** [comment]
Hello, as stated in the package documentation, it is compatible with Vue 2 and Vuetify 2 only, sorry.
I'm not currently using Vue 3 and Vuetify 3, but I'm opened reviewing a PR for this compatibility if you want (but I think it will probably requires a lot of work).
