### ISSUE TITLE
feat: Phone Input Extension

### ISSUE THREAD

**Issue by jssuttles** [paul-thebaud/v-phone-input#41]
## Expected Behavior
You can configure the input to accept extensions.

## Actual Behavior
It does not allow the extension to be entered in any format.

**Comment by paul-thebaud** [comment]
Hello, can you please give a documentation about what phone extensions are? Do you if this is supported by awesome-phonenumber?
Thanks.

**Comment by paul-thebaud** [comment]
After looking for other issues about extension in other projects (vue-tel-input, react-phone-number-input, awesome-phonenumber), it looks like extensions are complicated to handle, so I won't add this feature sorry.
Maybe the best solution for you is to add another dedicated input for extensions next to the phone input.
