### ISSUE TITLE
feat: support 3-letter Country ISO Code

### ISSUE THREAD

**Issue by flaviocordova** [paul-thebaud/v-phone-input#43]
Suggestion: Please consider also supporting 3-letter country ISO codes. 
Today my application uses this format (and maybe many others may use it too 😃) and it would be really hard to adopt another standard just to use v-phone-input (not considering possible conflicts with other packages)

**Comment by paul-thebaud** [comment]
Hello,
Because [awesome-phonenumber](https://github.com/grantila/awesome-phonenumber) does not support it, I won't add this to the package for now sorry. One solution could be to use a map between 2 and 3 country codes on your side.
