### ISSUE TITLE
feat: access the state of validation in auto validation

### ISSUE THREAD

**Issue by inventor7** [paul-thebaud/v-phone-input#44]
i want to use the auto validation but i can't know if the it's valid or not , there's deep down into the VInput ((isValid)) but i can't access it !

**Comment by paul-thebaud** [comment]
Hello @inventor7,
Could you provide a more precise of what APIs you would expect? And a code example using those hypothetical APIs?

**Comment by inventor7** [comment]
i just want to know how i could get the validation state of the phone input , if it's valid or not .
like on your website you are showing a live update of  "the phone validation state".

how you did that ?

**Comment by paul-thebaud** [comment]
OK. Best way to do this is to use [`awesome-phonenumber`](https://github.com/grantila/awesome-phonenumber) package (it is already used internally).

```typescript
import { parsePhoneNumber } from 'awesome-phonenumber';

const phoneNumber = '+33656...';
const isValid = parsePhoneNumber(phoneNumber).valid;
```
