### ISSUE TITLE
Using onlyCountries prop

### ISSUE THREAD

**Issue by iampapagray** [paul-thebaud/v-phone-input#7]
## Expected Behavior
From the docs, onlyCountries take an array of CountryIso2 (eg. GH). and this prod will be the only countries displayed

## Actual Behavior
After i add this prop and array, the component is no longer shown.

## Specifications

  - OS: MacOs
  - Browser: Firefox Developer Edition
  - Package version: ^3.0.0-alpha.5
  - Vuetify version: 3.0.3

Can you provide an example on how to use this flag ?

**Comment by paul-thebaud** [comment]
Hello @iampapagray,
Looks like you were browsing the `v2` documentation. The `v3` documentation is on the [next branch](https://github.com/paul-thebaud/v-phone-input/tree/next).
According to [the changelog](https://github.com/paul-thebaud/v-phone-input/tree/next), the `onlyCountries` property has been renamed to `includeCountries`.

You should use it as following:
```vue
<template>
  <v-phone-input :include-countries="['FR', 'US']" />
</template>
```
